### PR TITLE
minor typos in lesson 01

### PR DESCRIPTION
**Pull request by anenadic**

### CODE REVIEW

**Comment by gcapes** [comment]
Do you think `jekyll serve` is more useful than `make serve`? The Makefile rule runs the command `jekyll serve`, so it does the same thing. 

I should make explicit that the Make rule runs Jekyll, if I stick with `make serve` though.

**Comment by anenadic** [comment]
Well, that's partially my ignorance - I've never used the `make` wrapper, was not even aware it existed and when googled it before doing a PR - I could not find anything about it!

**Comment by anenadic** [comment]
Feel free to use whichever, it may confuse people who are not familiar with `make` - why is this suddenly used to run `jekyll`?

**Comment by gcapes** [comment]
Yep, fair point. Might as well remove extraneous load :)

**Pull request merged**
